# Generated by Django 5.0.6 on 2024-07-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='asignaturas',
            field=models.ManyToManyField(through='api.Inscripcion', to='api.asignatura'),
        ),
    ]
